apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "frontend.fullname" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "frontend.name" . } }
  template:
    metadata:
      labels:
        app: { { include "frontend.name" . } }
    spec:
      containers:
        - name: angular
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            { { - toYaml .Values.resources | nindent 12 } }
